### PR TITLE
Latest HTML changes to new repo

### PR DESCRIPTION
**Pull request by jmart518**
Starting a new

If you don't like the components modal stuff we can kill it

### CODE REVIEW

**Comment by danielperna84** [comment]
After testing the components modal I have to revert my opinion. I couldn't imagine how that would be from just seeing the picture. But it's indeed very sexy. We'll keep that. :)
What doesn't work though is the link to the keyboard shortcuts. The dev-tools in Chrome say:
`Refused to display 'https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`.

What I've missed and you can cut out are the `console.log` calls in the `apply_settings` function. Forgot those. Just while you're at it fixing the keyboard-modal. ;-)

**Comment by jmart518** [comment]
Oh yeah, that is left over from last nights tests

I have actually recreated the Ace Keyboard Shortcuts into the Configurator 👍 

Take a look, playing with different design ideas still:
screen shot 2017-02-08 at 3 44 09 pm

**Comment by danielperna84** [comment]
Looking great! :)

Another thing I already noticed before and didn't understand: The listst with the entites, events etc. are present twice in the code. When viewing the configurator from my PC it doesn't seem to matter. However on mobile the second list is being displayed underneath the filebrowser. I guess that's the second list. I'm not that much into CSS frameworks, so I'm unsure if the second set of lists is required for the mobile version to work, and having them visible is just a bug.

**Comment by jmart518** [comment]
Thanks!

Wow, can you get me a screen shot of that?  Both sets should never be viewable at the same time

**Comment by danielperna84** [comment]
Sure. It's a Samsung S4 (1920*1080) and the configurator accessed via chrome.

screenshot_2017-02-08-23-52-58

**Comment by jmart518** [comment]
Ok yeah those are supposed to be there since they shouldn't be in the main Editor view.  Basically mobile should be all Editor and all the "stuff" is tucked away in the sidenavs.  Hopefully that made sense, my brain is tired today :)

Do you also have them behind the sidenav on mobile?  Or do you think we should have those only viewable on desktops?

**Comment by jmart518** [comment]
`console.log` Is outta there

**Comment by danielperna84** [comment]
Hah! You're right. Totally ignored they would be missing completely if they weren't there. :D

**Comment by jmart518** [comment]
It does look like the padding between the filebrowser and the list needs to be tweaked some though

**Comment by danielperna84** [comment]
Yes, a little more visual separation would be nice.

**Comment by danielperna84** [comment]
Another minor improvement for people who don't know CTRL+F:
`editor.execCommand("find")`
If you place a search-icon next to the save-button people could search through their code more easily. The dialog is rather ugly, but I think theming for that can be done later, if possible at all.

**Comment by jmart518** [comment]
Ok cool, that'll be easy enough, but yeah theming it may be a whole different beast

**Comment by danielperna84** [comment]
And another one:
`editor.toggleCommentLines()` toggles comments on and off. Might be useful for people testing variations of their setup.
There is however no specific icon for comments. I would suggst just using a `#`. Is it possible to use such letters instead of icons without making it look bad?

**Comment by danielperna84** [comment]
I think I'll create an issue for additional commands. Those are probably out of scope for now.
What I've found though:
```
editor.execCommand("replace")
editor.execCommand("undo")
editor.execCommand("redo")
editor.execCommand("indent")
editor.execCommand("outdent")
```

**Comment by jmart518** [comment]
Good idea!

I added the search and you're right it's ugly, but functional for sure

**Comment by jmart518** [comment]
Fixed left sidenav, gave a little contrast too:

screen shot 2017-02-08 at 4 50 18 pm

**Comment by jmart518** [comment]
And search:

screen shot 2017-02-08 at 4 53 46 pm

**Comment by danielperna84** [comment]
I've just discovered, that the replace dialog just searches when no replacement value is entered. Do you think it might make sense to ditch the find and just use replace since it covers both?

**Comment by jmart518** [comment]
I agree, let's just use "replace"

**Comment by danielperna84** [comment]
Great. :) 
Time for bed now. As stated above, when you're done you can commit and push to your fork. Those commits will automatically be included here.

**Comment by jmart518** [comment]
Sounds good, I'll keep playing with this and push whatever I end up with

**Comment by jmart518** [comment]
Pushed my changes from today to my fork, didn't do a pull request.

Let me know your thoughts, off to bed

**Comment by danielperna84** [comment]
The button with those content-modifying option is awesome! Totally like that solution. And the preloader is a nice addition as well. Also the custom overview for the shortcuts looks great. :)
Do you plan to add the fold-button as well? If so, then I'll wait before merging this.

**Comment by jmart518** [comment]
Awesome, thanks!

Yeah I am just having trouble finding a nice icon to use for the fold button :)

The only thing I wanna make sure is that we don't have things in too many places where it gets confusing for the user

**Comment by danielperna84** [comment]
Well, you've used that angled arrow in the shortcuts overview. Why not stick with that?
Alternatives may be:
https://material.io/icons/#ic_all_out
https://material.io/icons/#ic_open_with
https://material.io/icons/#ic_swap_vert
https://material.io/icons/#ic_zoom_out_map

And yes, valid concern. Would it also be possible to place those buttons into a drop down menu like the one with the settings? Even though I really like the floating button, I feel it somehow would make sense to group them in a dedicated menu next to the settings. That way also captions are directly visible, and the floating button wouldn't occupy space in the editor.

What I images would be something like:
[ Open ] [ New (to do) ] [ Save ] [ Close (to do) ] [ undo ] [ redo ] [ find/replace ] [ fold ] [ Misc tools ] [ Settings ]

**Comment by jmart518** [comment]
That all sounds great to me, I like the idea of getting user feedback and going from there

Maybe having all those editing functions live in the floating button will be ok and logical.  

Thinking we leave [ Open ] [ Save ] [ Find ] [ Menu ] like it is since those are places to "get started or finish". Where as the floating button will be more of a during editing "activity"

If we end up with too much up top, it might get over whelming.  So if the floating button doesn't pan out, maybe a simple drop down from the top with all editing functions.  My main goal is to keep the amount of clicks and navigation to a minimum while still keeping the simple/clean interface

I'll add a couple more buttons to the fly-out of the float and we can do some more experimenting

**Comment by jmart518** [comment]
Added fold toggle, works great and looks good too I think:

screen shot 2017-02-09 at 11 25 27 am

**Comment by jmart518** [comment]
What do you think of something like this?  The new buttons are just place holders.  Not sure if the tooltip is too much:

screen shot 2017-02-09 at 1 06 41 pm

**Comment by danielperna84** [comment]
I think tooltips generally are a good thing as long as they are only visible when hovering the button with the mouse.

And yes, the fold button in the floating menu button are fine for me. And since we agree on waiting for feedback I'm good to go. Is there anything else you want to include, or are you ready for this to be merged? :)

**Comment by jmart518** [comment]
Made a small change to the save button, pushed and created a pull request

**Comment by danielperna84** [comment]
What I've just noticed: on mobile there's a bigger gab between the blue of the top bar and the editor. I think that's caused by the height of the toolbar being decreased, while the top-margin of the editor stays the same.

**Comment by jmart518** [comment]
You're exactly right, I noticed that too.  I'll have a look at that next

**Comment by jmart518** [comment]
Pushed Ace Editor fix to my repo, don't remember if I actually made a pull request :)

screen shot 2017-02-09 at 4 37 14 pm

**Comment by danielperna84** [comment]
👍 

Two things though:

1. On desktop the search-button now is missing
2. You can put the commands from the functions at the bottom (`editor.execCommand("replace");` etc.) directly in the onclick attributes. You just have to be aware of the quoting. So for it to work in double-quotes you can to `editor.execCommand('replace');` The result would be:

`<li><a class="waves-effect waves-light hide-on-med-and-up" onclick="editor.execCommand('replace');"><i class="material-icons">search</i></a></li>`

This only doesn't work for folding, because there it uses different functions depending on which state we're in. And not using dedicated functions would save some filesize.

**Comment by jmart518** [comment]
Oh nice!  Let me do some cleaning up and I'll push an update

**Comment by jmart518** [comment]
Fixed Search, whoops!

Ditched functions and added them inline

Here comes an updated version

**Comment by danielperna84** [comment]
Works like a charm! :)
Ready to have this pulled?

**Pull request merged**
