### PR TITLE
First merge for next release

### PR DESCRIPTION
**Pull request by jmart518**
I've added the new mobile concept, looks much better (though not functional yet)

Initial cleanup/beautify Search box

### CODE REVIEW

**Comment by jmart518** [comment]
New mobile view:

screen shot 2017-02-10 at 8 20 59 pm

**Comment by danielperna84** [comment]
That's really neat! :)

Two things:

1. You can easily implement the Close-Button. The onclick-attribute should then look like:
`document.getElementById('currentfile').value='';editor.setValue('');`
2. Last night while failing to sleep I thought about creating new files. This actually won't need any modification on the backend, so if you want to you can implement it too. The way files are being saved is, that the path of _currentfile_ (the same element as above) is passed to the backend, along with the content of the editor. Since we can't modify _currentpath_ at the moment, this always overwrites the currently opened file.
Now if the currentfile-input wouldn't be type hidden but instead a text and somehow displayed, the users could modify the filename, thus allowing to save to an alternative filepath. Out of the top of my head there would be a single row above the editor in the form of _File: /path/to/file_, where the trailing part would be the input box which users could modify. The code of the button for the new file would then be:
`editor.setValue('');document.getElementById('currentfile').value=document.getElementById('fbheader').innerHTML;document.getElementById('currentfile').focus()"`
With that the users would only have to append `/whatever` to the text box and hit the save button.

What do you think about that solution? A little improvement which would require a small change on the backend would be to automatically set a default filename like `/newfile`. The change on the backend would be needed because we currently don't know for sure which directory-separator the filesystem we're writing to is using (yes, there are Windows users, for which it's `\` instead of `/`, and the most reliable way of figuring that out is using Pythons os.sep method).

**Comment by jmart518** [comment]
My thoughts exactly, this is what I've been working on:

screen shot 2017-02-11 at 9 48 51 am

Where the info is populated by fbheader/filename.extension (currently just static info)

**Comment by danielperna84** [comment]
Ok, then move the input-hidden up there, make it a input-text, apply styling, and everything should keep working as before, with the advantage of being able to specify the filename. :)
And you shouldn't rely on the fbheader for the path for the reasons mentioned above. The exact information we need there is already what we have in the _currentfile_ input im talking about. :)

**Comment by jmart518** [comment]
Ah perfect, I didn't snap when you were talking about _currentfile_ earlier, it's now working awesome, including saving a file to a new name.

Haven't figured out how to implement readonly to the filepath only yet.

**Comment by jmart518** [comment]
Is there any way to call a refresh of the filebrowser?  Right now, a manual refresh is required to see the new files

**Comment by danielperna84** [comment]
The `readonly` attribute only works with input elements. If you have that already, it should be something like:
```html
<input type="text" value="foo" readonly />
```

Another thing:
I have pushed a new configurator.py to the dev branch. I've done some small changes to the API.
1. POST-requests now always return JSON with all sorts of different information in it. This breaks a tiny bit of the current code. Until now the `save()` function directly puts the return value into the toast. Since the return value now is an object, we don't see what we want anymore. The quick fix would be to replace `... + resp + ` with `... + JSON.stringify(resp) + ...`
2. There's now an API-method to delete files / folders. You could add a `delete()` function that looks something like this:
```javascript
function delete() {
    var path= document.getElementById('currentfile').value;
    if (path.length > 0) {
        data = new Object();
        data.path= path;
        $.post("api/delete", data).done(function(resp) {
            var $toastContent = $("<div><pre>" + JSON.stringify(resp) + "</pre></div>");
            Materialize.toast($toastContent, 2000);
            listdir(document.getElementById('fbheader').innerHTML)
        });
    }
}
```
3. Yes. If you haven't yet converted the fbheader to an input-element, you can do `listdir(document.getElementById('fbheader').innerHTML)`. Otherwise it would be `.value` at the end. This should actually be called right after saving or deleting a file. Not with the button itself though. Instead within the corresponding function. I have it like that in the HTML-snippet above.

**Comment by danielperna84** [comment]
One more thing:
Having the `#fbheader` as an input would enable the users to manually enter a path and directly jump into that directory. But that would require some more JavaScript I would first have to think about. Hence readonly, so people don't expect the element to do anything.

**Comment by jmart518** [comment]
Nice, the save + filebrowser update worked perfect!!

I'm going to update my configurator.py to the your dev so I can start testing delete as well as update the save function

Cool, I haven't made any changes to fbheader.  I like the way it works currently

**Comment by danielperna84** [comment]
Another thing I had in mind with fbheader being an input-text: creating new directories. The soltion you now already have only creates files. There has to be a way to create folders as well, and using the fbheader seemed like a possible source for a foldername since it is displayed in the filebrowser-context. But no worries, you can leave it as a span and we'll take care of that as soon as people realize they can't create folders. :D

**Comment by jmart518** [comment]
Ha!  I definitely like the idea of creating folders, let me get these couple things updated and then I'll push an update for you to play with.

Then we can go from there on getting the cool folder creation/renaming going

**Comment by danielperna84** [comment]
Regarding creating folders:
How about a little icon [create_new_folder](https://material.io/icons/#ic_create_new_folder) somewhere at the top of the filebrowser? Clicking that should popup a modal asking for a folder-name, an then call a (not yet existing) function `newfolder(foldername)`. You could prototype the function for testing like this:

```javascript
function newfolder(foldername) {
    console.log(foldername);
}
```

Of course it doesn't have to be _foldername_. Not being a native speaker I'm always a bit confused if it's a folder or a directory. :D

**Comment by danielperna84** [comment]
I've pushed again (configurator.py), this time including an API-method to create folders. The JavaScript function could look like this:

```javascript
function newfolder(foldername) {
    var path = document.getElementById('fbheader').innerHTML;
    if (path.length > 0 && foldername.length > 0) {
        data = new Object();
        data.path = path;
        data.name = foldername;
        $.post("api/newfolder", data).done(function(resp) {
            var $toastContent = $("<div><pre>" + JSON.stringify(resp) + "</pre></div>");
            Materialize.toast($toastContent, 2000);
            listdir(document.getElementById('fbheader').innerHTML);
        });
    }
}
```

**Comment by jmart518** [comment]
I'm getting an error when adding in `function delete ()`

Filebrowser is empty and the console is showing an error of: _Uncaught SyntaxError: Unexpected token delete_

**Comment by danielperna84** [comment]
Without seeing the code it's hard to tell. One thought though: maybe delete is a keyword in JavaScript and that's why it throws the error. Try renaming it to something else.
Btw., I'm outside, so can't reply that often and got bad signal too. I'll be home again in about 4 hours. Hope you can find a solution for the error in the meantime.

**Comment by jmart518** [comment]
Brilliant!  That was it, renamed fixed it and now we have delete working.

I did notice that after the file is deleted the contents stay in the editor, so I'm thinking about adding a clear to this as well.  Thoughts?

No worries, enjoy your time outside, I'm juggling this and home remodel things today/tonight

**Comment by danielperna84** [comment]
Yes, deleting the content of the editor makes sense. `editor.setValue('')` would be the way to go. :)

**Comment by jmart518** [comment]
I ended up using: `document.getElementById('currentfile').value='';editor.setValue('');` so it would clear out the currentfile info as well

Haven't been able to get the new folder creation working yet, I think I'll upload what I have so you can take a peek

**Comment by danielperna84** [comment]
That's a plan. For me it's time for bed now. I'll look at it tomorrow. :)

**Comment by danielperna84** [comment]
Been testing, fixing and improving. I have pushed a new configurator.py. With the new one your dev.html will probably not work anymore. It injects the OS-dependent separator, which turnd out to be very handy.

As I'm the "receiver" of your PR, GitHub allows me to make changes to the code that's going to be merged. I have therefore updated the dev.html and configurator.py in your repository. So you already have the lastest state, and to keep working on it you just have to use the code that's in the repository right now.

Two things that could be changed:

1. There are three elements in the code for "New File". By trial and error I found out, that the first and last one are relevant. What's the one in the middle for?
2. The buttons in the searchbox (RegEx, caps, word) are, in my opinion, not obviously coloured when checked, It's just a very slight shift barely noticiable. I would prefer a little more change to make it visually clear what has changed.

Anyhow, check out my changes. I really love what this is evolving to. :)

**Comment by jmart518** [comment]
Awesome!  New folder is working great now

1.  Not sure I'm following, are you talking about `document.getElementById('currentfile').setSelectionRange(document.getElementById('currentfile').value.length-7,document.getElementById('currentfile').value.length);` If so, it looks to be the highlight/selection of the "newfile" name (which is very cool by the way!)

2.  The find/replace is still "under construction" theming it to look nice has been a pain.  It'll get better :)

On another note, do you think it's too busy on the right hand side of the navbar on desktop?  Maybe moving _New Folder_ and _New File_ to the left by the Filebrowser button would even things out.

I agree, this really is shaping up to something special.  I actually find myself using it a lot for my HA config changes now, maybe even more than Atom ha!

**Comment by danielperna84** [comment]
First of really quick: I'm doing another optimization in dev.html. So be patient for a moment before continuing.

**Comment by danielperna84** [comment]
Ok, you can continue now. Sorting the lists of entites etc. didn't work for mobile. I now have created a dedicated function for sorting, which reduces the amount of code and now also includes the lists in the mobile view.

1. Uhm, I'm confused myself. I don't find what I was talking about anymore. Ignore that then.
2. Ok. Although it's already looking great. The changes I have suggested would have been the only task I would see to be done.

Yes, it does kind of look busy. But I would let the users decide if they want some of that hidden. Ultimately having the buttons direct at hand makes working with this quicker. So I tent to leave it that way.

**Comment by jmart518** [comment]
No worries, I'm headed out to my nephews birthday party.  Be back in a few hours

Also something VERY minor I noticed while creating a duplicate folder:

screen shot 2017-02-12 at 9 43 34 am

Is there an easy way to change the terminology from file to folder?  That way it reads _Folder Exists_

**Comment by danielperna84** [comment]
The error message is the raw one the system returns. On Windows it looks different. And internally, folders are just files in linux. So it's technically correct and I wouldn't change that.

**Comment by jmart518** [comment]
Ok cool, I can live with it :)

I may have described what I was thinking about the navbar wrong, here's a screen shot:

screen shot 2017-02-12 at 10 12 14 am

"Directory" actions on left, file actions on right.  Keeping everything quickly accessible is definitely the goal with all of this.

**Comment by danielperna84** [comment]
Oh, yes, that look good as well. Before you leave please push your changes, so I can keep working based on your modifications. :)

**Comment by jmart518** [comment]
Wow buddy, just got back and you have been busy, awesome stuff!

**Comment by danielperna84** [comment]
Still working on a per-element dropdown menu. That's tricky though.

**Comment by danielperna84** [comment]
Ok, commited my last state. For now I don't understand why the dropdowns don't work. I assume it's because the attached elements aren't present when the materialize library does it's magic. Or maybe some styling issue. If you want you can have a look at it. Main action is in the `renderitem` function.

Time for bed now for me.

**Comment by danielperna84** [comment]
Commited another small fix. But that doesen't solve the problem. If it would work, there should be a menu that pops up an alert box when clicked.

**Comment by danielperna84** [comment]
Ok, found the issue. It's being display now, but now fully visible. This is a styling issue now, so I hope you may find a solution.
Now I'm not messing up my mind anymore. :D

**Comment by danielperna84** [comment]
And an issue I see now: when the scrollbar in the filebrowser is visible, this messes up the height of the rows. Should be fixable by decreasing the width of the left element, although we'll loose some space for content then.

**Comment by jmart518** [comment]
Awesome!  It's dinner and fam time, then I'll hop on and see what I can figure out

**Comment by jmart518** [comment]
Committed a filebrowser dropdown fix.  Very strange dropdown behavior when you scroll down to the items lower on the list though.

Also, I noticed that `        .side-nav a {
          padding: 0 16px;
          display: inline-block;
        }
` has broken the right side-nav somewhat, so we need to individualize this style.

**Comment by danielperna84** [comment]
I have decreased the width of the filenames, and the stats-line now also has a smaller font. Looking better now and it doesn't mess up the layout as much anymore.
The strange dropdown behavior is still present. Seems as if those menus don't adapt to the scroll-position within the side-nav and instead rely on the main contents scroll position, which of course doesn't change.

**Comment by jmart518** [comment]
Looks great with the smaller font.

I just pushed an update with the right side Ace settings side-nav fix

**Comment by danielperna84** [comment]
And I found a fix for the offset dropdown menus: `#fbelements` needs `position: relative`. Or you still working on this or can I keep on going with conflicting with your code?

**Comment by jmart518** [comment]
Please keep working on it, I haven't made any changes in a bit

What do you think about adding a "selected" class to the selected file?

**Comment by danielperna84** [comment]
I was thinking about that myself. But since people are able to browse the whole filesystem without actually closing the file in the editor, it will be kind of tricky to track that and mark the row active as soon as the user is back in the folder. Maybe in the future, but not for the next release.

I have fixed everything now that came to my eye. The dropdowns in the filebrowser are working and the delete button in there does it's job. Because of that I removed the other delete buttons. I think deleting directly from the filebrowser is more intuitive and invites less to misusage.

I'd actually like to get a new release out soon. The new features (new files and fodler etc.) appear very useful and I bet the people would like that. So if you don't see anything wrong with the current status, I would merge the PR. :)

**Comment by jmart518** [comment]
Everything is looking good to me!

I am curious though, did you mean to remove the delete drop down below `menubutton.setAttribute('data-beloworigin', true);`?

Having it drop below may help accidental double clickers

**Comment by danielperna84** [comment]
Yes, that was on purpose. Double clickers still have to confirm deletion, so I think it's not that big of a deal.

**Comment by jmart518** [comment]
You can remove lines 216 - 218 also:
`        .ace_search .right {
            background-color: purple;
        }
`

**Comment by danielperna84** [comment]
Done. :)

**Comment by jmart518** [comment]
I'm going to make one more minor change to the search button (temporary fix)

**Comment by jmart518** [comment]
That will put a border around the small search option buttons

**Comment by danielperna84** [comment]
Looking good. Anything else? :)

**Comment by jmart518** [comment]
I think that's a good place to leave it and roll out an update.  This is an awesome release!

**Comment by danielperna84** [comment]
It sure is. Merging then. :)

**Comment by jmart518** [comment]
Did you see this yet? [https://community.home-assistant.io/t/simplistic-configuration-ui/10175/76](url)

**Comment by danielperna84** [comment]
Yes, but until that's done people still might enjoy our work. And who knows which features he will include. I think having this in parallel is still of value. Even if we won't have to edit our yaml anymore, there's a lot of other stuff on my Raspberry that I can edit much easier now. :)

**Comment by jmart518** [comment]
I agree, this has become a powerful tool

**Comment by jmart518** [comment]
I just found some left over unnecessary code that I have now removed.  Nothing major, so it can wait until the next release.  Just an fyi

**Comment by danielperna84** [comment]
You should take care of that as soon as there is a new dev-branch. Currently I'm confused why a small fix needed for embedding isn't displayed here, even though it says it's commited.
Could you please try copying the configurator.py from the dev branch and see if it works for you?

**Comment by jmart518** [comment]
Copied over, running now, everything appears to be working.  Is there anything specific I should check?

**Comment by danielperna84** [comment]
No, without the fix it didn't start at all, and when I fixed that the filebrowser was empty. But That's both things you would have noticed. :D 
Ok, merging this into master then. :)

**Comment by jmart518** [comment]
I've made some changes to the UI as well as some cleanup.  I'll commit it as soon as we have a new dev branch.  Unless you'd prefer I push it to the existing one

What are your thoughts on a file uploader?  No sure how to implement on the backend, but was thinking it might be pretty useful

**Comment by danielperna84** [comment]
There already is a new dev-branch. :) The easy route would again be to delete and re-fork.

**Pull request merged**
