### PR TITLE
FB Sidenav Change

### PR DESCRIPTION
**Pull request by jmart518**
Not sure if you plan on updating anymore, but I did a slight redesign and cleanup of the filebrowser sidenav

### CODE REVIEW

**Comment by danielperna84** [comment]
I'll have a look at it later today. :)

**Comment by danielperna84** [comment]
Even though it's looking better now, there's one thing I dislike about switching the rows in git-directories: when leaving a git directory, the link I have to click to move further up the path moves away from my current cursor position. So if I were to repeatedly click to get to my filesystems root, I'd have to pay attention to where I click.

**Comment by jmart518** [comment]
Ah yeah I gotcha, because the branch selector disappears, causing the directory and back button shift up now.  

May have to revert their positions.

The lag has always been noticeable to me on my setup.  The "Add" button appears to be the culprit

I'll keep plugging away at it

**Comment by jmart518** [comment]
Pushed a new update to the fb sidenav

I temporarily moved the new branch button under Branches.  This eliminated all the lag, but does require an additional click in order to add a new branch.

Let me know your thoughts

**Comment by danielperna84** [comment]
I liked the + more. Given the context it's fairly obvious what the button is doing. Occupying an extra row among all the branches one may have, I don't think that's the way it should be. But since you've said "temporarily", I assume you'll be bringing the button up again. :)
What's also wierd is, that the path-row streches vertically when opening the branch-dropdown.

**Comment by jmart518** [comment]
I liked the + where it was before too, much much better visually.  However it causes weird behavior of the branch selector (lag and just overall janky-ness)

Playing with different options, to see if we can "have our cake and eat it too"

The path-row isn't actually stretching, it's the branch selector that's dropping down and "out" towards the user.  You can change the animation back by removing `popout` from line 1232 `<ul class="collapsible popout no-padding" data-collapsible="accordion">`

**Comment by danielperna84** [comment]
I have added `git init` to the last state of your repo. Hope you haven't made complex changes since then. Although minde are rather minor. Works surprisingly well.

I also have tested your code without the popout, and I like that more. It reacts instantly, just like I would expect, and everything stays in place. As you may notice: I'm not the biggest fan of unexpected movement in the UI. ;-)
If you're fine in leaving it the way it is but sripping out the popout, that would be the way to go I think. Oh, and the colors don't match the surrounding. Even though that blue-tone is present elsewhere, the filebrowser on it's own is pretty much grey scale. So either the rest gets more color, or the colors of the dropdown should be replaced with some grey tones.

Another thing: is there some way to disable items in dropdown menus? Thinking about the git dropdown here. git init only makes sense in directories that are not repositories. On the other side, git commit only makes sense when we're in a repository. Woudl be nice to somehow only provide the actions people can really execute.

**Comment by danielperna84** [comment]
I have now also added the `check_config` API of HASS next to the restart item. Due to the way this is implemented people will have to keep an eye on HASS to see (and dismiss) the notification and also have a look at the dev-info section to see details about the error. This has the effect, that as long as the notification in HASS is not dismissed, the configurator will think the configuration is valid if further checks are triggered. But I think this still is beneficial compared to how it was before.

**Comment by jmart518** [comment]
Uh oh, I didn't know about the above changes you made. Hopefully my changes don't interfere too bad.

I'll update my stuff to match yours

**Comment by jmart518** [comment]
Give that one a go, I think you'll like these latest changes :)

**Comment by danielperna84** [comment]
You're right, I like that. Except the popouts. Either hovering all elements in the filebrowser pops them out, or none. The mix is wierd. And my tendency to prefer less eye-candy shouldn't be new by now. :D 
The way it's now is that there are those subtle highlights when scrolling up/down the list, and then when you hover the branch-row it's like a visual slap. In terms of what those elements do it does indeed make sense to visualize their differentness. But a little more "subtlety" (is that a word?) would be a place in the middle to head to. :)

**Comment by danielperna84** [comment]
Oh, and I would replace the GitHub Icon with something like this:
http://www.flaticon.com/free-icon/git-logo_52234#term=git&page;=1&position;=3
Git-Integration doesn't necessarily has to mean GitHub-Integration.

**Comment by danielperna84** [comment]
While you're at it: the git init and git commit modals can use the new icon as well. And the new about dialog looks great. :)

**Comment by jmart518** [comment]
Give that latest commit a go, I found a couple mistakes in the HTML code that may have caused strange layout issues.  Everything works for me, but I want to make sure I didn't break something during house cleaning

Oh and I added the git icon to the various git modals

**Comment by danielperna84** [comment]
Looking good to me. :)
Anything else you want to have done? I'd like to have a look at getting some unsaved-warning in there, but that'll have to wait until tomorrow.

**Comment by jmart518** [comment]
Awesome!

That'll be the last commit for me today

**Comment by danielperna84** [comment]
The save-button now reflects the "dirty-state" of the editor. How do you like that solution? I find marking it red is obvious enough and spares us from adding another modal.

**Comment by jmart518** [comment]
Yeah I think that should do the trick, simple yet effective

**Comment by jmart518** [comment]
We could instead change the filepath input to red when changes are unsaved, what do you think about that?  Too much?

screen shot 2017-02-26 at 9 51 47 am

**Comment by danielperna84** [comment]
Thought of that before myself. But for one, it's a very dominant visual result, and second, it might not be too obvious what the "problem" is. For me this would indicate that the path is somehow invalid.
Highlighting the save-button feels to be the clearer way of telling the user a save-operation has to be done. Originally I wanted to have the save-button disabled as long as there is nothing to save. But since these aren't really buttons that didn't work out.

**Comment by jmart518** [comment]
Ah yes, you are right, it definitely makes it look like an invalid path

**Comment by jmart518** [comment]
If you would like to disable the save button until changes are present, we could always add a new class, something like:
`.noclick {pointer-events: none;}` and add/remove it depending on the state of the file

**Comment by jmart518** [comment]
That latest commit will "hide" the save button until a file change is detected

**Comment by danielperna84** [comment]
Looking good. Although the noclick becomes obsolete when the button is hidden.

**Comment by jmart518** [comment]
:) I put hide in "" because it's not really hidden.  The button is still there, but color matched to the navbar.

It was a last minute idea, but going with `visibility:hidden` is a much better implementation (already done on my local copy)

**Comment by jmart518** [comment]
What are your thoughts on keeping the Close File button hidden until a file is loaded?

**Comment by danielperna84** [comment]
I like it. That what the 👍 was meant for. I was sceptical at first, but it works well, and having it that way tells the user exactly what's possible and what not. Having the save-button in red still emphasizes it's presence. So we could actually leave the button red all the time and strip out the JS that handles adding/removing the class.

**Comment by jmart518** [comment]
I'm not sure the best way to implement the hiding of the Close File button.  Similar way, but on file load we add the class and file close would then remove the class?

**Comment by danielperna84** [comment]
I actually wouldn't hide the close button. I think that would make more sense as soon as there are tabs that can be closed. Right now it's not really a "close" button in the sense of that word. It's rather a "clear"-button with no direct relation to the file. And clearing can happen at any time, even when no file (content) is loaded.

**Comment by jmart518** [comment]
Ah yes, you are exactly right.  So really we could have it shown only when there is text in the editor or just like you said, not even mess with it until we implement tabs.

**Comment by danielperna84** [comment]
I'd go with not messing with it. And when the save button is initially hidden I would see this ready to be released. 🙂

**Comment by danielperna84** [comment]
Or one more minor change: We could use a modal that's telling us that the filepath is missing. Right now when we click save but there's no filepath, it will just fail silently (there's no else in the `save` function).

**Comment by jmart518** [comment]
I think that's a great idea 👍 

I also keep wondering if we should still implement an alert or modal when trying to load a new file and a change is still unsaved.  The bright red save button is nice, but it would be good to have a fail safe.  Something like "Discard changes and load file?"

**Comment by danielperna84** [comment]
I agree. Do you to handle those remaining tasks?

**Comment by jmart518** [comment]
I'll give it a shot :)

But if you're wanting to release soon, you may want to knock them out instead ha!

**Comment by danielperna84** [comment]
I'm not in a hurry. Take your time. :)

**Comment by jmart518** [comment]
Wow, this is proving to be more difficult than expected. My js skills are very low :-( . Any hints/tips?

I also don't get the silent failure when saving without the pathname.  Maybe I'm misunderstanding, but it appears that without a path included, the file gets saved to the "Basepath"

**Comment by danielperna84** [comment]
Uhm, it's ok if you just create the modals. You're better with UI. I'll then do the JS part.

About the silent failure: If you copmletly refresh the the tab, the input with the filename is empty. If you enter some text in the editor, the save-button becomes visible. This is like creating a new file on the fly, but to save it the path must be provided.

**Comment by jmart518** [comment]
Ah ha! Now I see what you're saying, thanks for clarifying on the save issue

I've added an alert dialog for the save without path as well as a new modal `modal_markdirty` I'll commit the changes now

**Comment by danielperna84** [comment]
I think I get were you got stuck. The modal doesn'r provide a return value which could be used in the loadfile function. How do you like my workaround?

**Comment by jmart518** [comment]
That works perfect, I like it!

I just pushed a change to when it detects the missing filepath, that way the user doesn't need to go through the save modal in order to find out the path is empty

**Comment by jmart518** [comment]
In the new modal, close file does just that, it only closes/clears the file.  It doesn't load the newly selected file.

Same with the save.  It seems more natural to save and then load the new file.

Hopefully that makes sense

**Comment by danielperna84** [comment]
1. Good idea with the save_check function.
2. Uhm, yes, that's how I wanted it to be like.

**Comment by danielperna84** [comment]
Somewhere with your changes we've lost the unsaved-warning when switching from an edited file to a new file.

**Comment by jmart518** [comment]
I'll take a look right now

**Comment by danielperna84** [comment]
The way I've done it before was looking if the save-button had the red-class. This now has to be adjusted to your modifications.

**Comment by jmart518** [comment]
I tracked it down, I'll commit a fix in just a bit

**Comment by jmart518** [comment]
There we go, I kind of like having the red on the save button again.  What are your thoughts?

**Comment by danielperna84** [comment]
I like the red as well. Without it some people may not even notice there was a change in the UI. The red is a great way of telling the user "you better be saving!". :)

**Comment by danielperna84** [comment]
Anything else you want to add to this, or are we ready for a release?

**Comment by jmart518** [comment]
That is all from me for this go around

Let's let her fly

**Pull request merged**
